### ISSUE TITLE
Fails to compile; missing an import Foreign.C.Types in Finalizer.hs

### ISSUE THREAD

**Issue by cactorium** [HIPERFIT/hopencl#12]
I'd send in a push if I knew how to :/. Adding that seems to make it buildable and it runs through 74/77 tests correctly afterwards. Thanks for the awesome project and sorry for being vague and unhelpful. I'm guessing it broke because of a GHC update..?

**Comment by kfl** [comment]
What version of Haskell Platform are you using?

It works fine (it compiles and `cabal test` does not complaint) using haskell platform 2012.4.0.0.

**Comment by cactorium** [comment]
Heh, that is a very good question. I'm running Archlinux so I got ghc and cabal-install from the main repos, and installed all the dependencies using cabal. The important bit I'm guessing is that ghc is version 7.6.3, compared to 7.4.2 for the official platform, so I'm apparently on the unstable edge of things by mistake. Heh, something to fix in several months..?

**Comment by kfl** [comment]
OK. Could you copy the error message you get? Because I can't see why `Foreign.C.Types` should be needed.

**Comment by cactorium** [comment]
kelvin@batman:~/hopencl$ cabal build
Building hopencl-0.2.1...
Preprocessing library hopencl-0.2.1...
[ 7 of 15] Compiling Foreign.OpenCL.Bindings.Internal.Finalizers ( Foreign/OpenCL/Bindings/Internal/Finalizers.hs, dist/build/Foreign/OpenCL/Bindings/Internal/Finalizers.o )

Foreign/OpenCL/Bindings/Internal/Finalizers.hs:60:1:
    Unacceptable result type in foreign declaration:
      IO Foreign.C.Types.CInt
    When checking declaration:
      foreign import ccall safe "static CL/cl.h clRetainContext" clRetainContext
        :: ClContext -> IO ClInt

Foreign/OpenCL/Bindings/Internal/Finalizers.hs:63:1:
    Unacceptable result type in foreign declaration:
      IO Foreign.C.Types.CInt
    When checking declaration:
      foreign import ccall safe "static CL/cl.h clRetainCommandQueue" clRetainCommandQueue
        :: ClCommandQueue -> IO ClInt

Foreign/OpenCL/Bindings/Internal/Finalizers.hs:66:1:
    Unacceptable result type in foreign declaration:
      IO Foreign.C.Types.CInt
    When checking declaration:
      foreign import ccall safe "static CL/cl.h clRetainProgram" clRetainProgram
        :: ClProgram -> IO ClInt

Foreign/OpenCL/Bindings/Internal/Finalizers.hs:69:1:
    Unacceptable result type in foreign declaration:
      IO Foreign.C.Types.CInt
    When checking declaration:
      foreign import ccall safe "static CL/cl.h clRetainKernel" clRetainKernel
        :: ClKernel -> IO ClInt

Foreign/OpenCL/Bindings/Internal/Finalizers.hs:72:1:
    Unacceptable result type in foreign declaration:
      IO Foreign.C.Types.CInt
    When checking declaration:
      foreign import ccall safe "static CL/cl.h clRetainEvent" clRetainEvent
        :: ClEvent -> IO ClInt

**Comment by dybber** [comment]
I just tested it on a GHC 7.6.1 installation and get the same error, something has changed since between 7.6 and 7.4. 

I will look into it. Thanks for the report.

**Comment by kfl** [comment]
For reference: it doesn't hurt GHC 7.4.2 to include `Foreign.C.Types` in `Finalizers.hs`. I guess that GHC 7.6 can actually understand the C type alias, and can see that an `cl_int` is the same as a normal C `int`. Interesting.

**Comment by dybber** [comment]
http://www.haskell.org/pipermail/haskell-cafe/2011-November/096673.html

**Comment by dybber** [comment]
So the problem is that CInt is a newtype and we have to import its constructor

> import Foreign.C.Types (CInt(..))

**Comment by kfl** [comment]
It is somewhat frustrating that we don't export `CInt` but `ClInt` and we just have to know that they (currently) are the same.

**Comment by dybber** [comment]
Perhaps Foreign.OpenCL.Bindings.Internal.Types should just export the
complete Foreign.C.Types module? Or do you have any other suggestion?

## 

Martin Dybdal

**Comment by kfl** [comment]
I'm not sure I have an other suggestion. I just don't understand why we have to import the `Foreign.C.Types` module. Because on some platforms the C types `int` and `cl_int` could be different (a common case could be that `int` is 64 bits and `cl_int` is 32 bits, for instance).

Is it because `ClInt` is exported abstractly? Because we don't export any types directly from `Finalizable.hs`.

**Comment by dybber** [comment]
No, `ClInt` is just a type alias for `CInt` (determined by c2hs from the OpenCL headers). The problem is that `CInt` itself is a newtype which should be imported, including all constructors, at the point where we do the FFI imports. But you are right, in another situation `ClInt` could perhaps be a type alias for `CLong` and then the fix I committed wouldn't work.
